### ISSUE TITLE
Mac/OSX doesn't always block

### ISSUE THREAD

**Issue by nkabbara** [bradjasper/focus-CLI#1]
Hi Brad,

Nice script.

I noticed that it doesn't always work right on macs because you'll need to add IPV6 version of the routes.

Example: 

0.0.0.0 metafilter.com
::  metafilter.com
0.0.0.0 reddit.com
::  reddit.com

I don't know much bash; are you planning on implementing this anytime soon?

Thanks.

**Comment by bradjasper** [comment]
Hey @nkabbara thanks for reporting this. I haven't hit this issue myself––could you provide a bit more info?

What version of OS X does this happen on?
Does it always happen? Or only for some cases (if so, which?)
What happens if you type "ping hostname.com" after you're in focus mode? Does it resolve to 127.0.0.1 or the actual IP?

Reason I ask is sometimes local programs cache DNS (like Chrome). So if you go into focus mode, you might need to restart them.

**Comment by nkabbara** [comment]
Hi Brad,

When the script didn't block on my laptop, I did some googling and found this: http://stackoverflow.com/questions/6841421/mac-osx-lion-dns-lookup-order

Then I tried it on my mac to see if this was the case by adding :: reddit.com to the hosts file. Then reddit started blocking. Whereas before it wasn't.

Also, I tried http://selfcontrolapp.com/ and I noticed that it was working. Looked into hosts file and it was adding the :: version as well.

> What version of OS X does this happen on?

OSX 10.8.3

> What happens if you type "ping hostname.com" after you're in focus mode? Does it resolve to 127.0.0.1 or the actual IP?

It resolved to 127... But not on the browser.

**Comment by bradjasper** [comment]
Hey @nkabbara thanks for the additional info. I've added an ipv6 line via commit 88693700d1b922d537c7723dbc28032c8a1f985a which I think should take care of this (unable to hit the same issue so I haven't been able to test).

Another issue sometimes related to this, I noticed if you list the same hostname twice it has issues––maybe something else to check?

**Comment by nkabbara** [comment]
Thank you!

I'm not listing it twice. I hope this works.

On Tue, May 14, 2013 at 3:51 PM, Brad Jasper notifications@github.comwrote:

> Hey @nkabbara https://github.com/nkabbara thanks for the additional
> info. I've added an ipv6 line via commit 8869370https://github.com/bradjasper/focus/commit/88693700d1b922d537c7723dbc28032c8a1f985awhich I think should take care of this (unable to hit the same issue so I
> haven't been able to test).
> 
> Another issue sometimes related to this, I noticed if you list the same
> hostname twice it has issues––maybe something else to check?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradjasper/focus/issues/1#issuecomment-17904187
> .

## 

For new feature updates & special offers please "Like" our Facebook
pagehttp://www.facebook.com/zipzoomauto
.
You may also follow us on twitter @ZipZoomAuto

-Nash

**Comment by bradjasper** [comment]
Hey @nkabbara I'm closing this. Please let me know if it's still an issue!
