### ISSUE TITLE
How to block application with focus-CLI

### ISSUE THREAD

**Issue by philohistoria** [bradjasper/focus-CLI#2]
Hi Brad,
I found your app very useful. The Mac/OSX app has a function to also block applications. However, this command line version only specifies how to block websites. Could you give some hints on how to use command line tools with focus to block applications?

I also read your blog but does not get a clud of how to block applications.

http://bradjasper.com/blog/case-study-focus/

Thanks very much!

**Comment by bradjasper** [comment]
Hello, the main Focus app (https://heyfocus.com/) is the best way to accomplish this and has some scripting capabilities (https://heyfocus.com/docs/features/scripting/). If you are looking for help with the main Focus app I can help best at support@heyfocus.com.
